/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adam/.choosenim/toolchains/nim-0.18.0/lib -o /home/adam/Documents/Projects/nim-hashids/nimcache/hashids_hashids.o /home/adam/Documents/Projects/nim-hashids/nimcache/hashids_hashids.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg {
NimStringDesc* salt;
NI minHashLength;
NimStringDesc* alphabet;
NimStringDesc* seps;
NimStringDesc* guards;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NU8 tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg;
typedef tySequence_qwqHTkRvwhrRyENtudHQ7g* tyArray_pr9btTEBWiYSIlBNDlIa66w[2];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw {
tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* h;
tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* e;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A {
char dummy;
};
struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ {
long flags;
void* study_data;
long match_limit;
void* callout_data;
void* tables;
long match_limit_recursion;
void* mark;
void* executable_jit;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_zG9bFJ68RP1XeAeJialvJfw)(NimStringDesc* salt, NI minHashLength, NimStringDesc* alphabet);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_oFYJKP7L2EphXb9ajR83NJg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_6e5MGL10HDAJ205lBYpWxw)(NimStringDesc* s, NIM_CHAR c);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_bKoQGynT9bWCEn79aXG8be9aw)(NimStringDesc* s, NimStringDesc* sub);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qhashids)(NI a, NI b);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg flags);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, replace_XTFad3adT9ckW2xJiSYMhMw)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_O07h2h9cUM2mHUfR3Dz1paA)(NimStringDesc* salt, NI minHashLength);
N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_whSPG9bOGCvpSoqgm7w29cbQ)(NimStringDesc* salt);
N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_pHmRwdP59aPVoZIoyNFP9czg)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encode_D0RXiba7bli9byNMlD9bhjRg)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, tySequence_qwqHTkRvwhrRyENtudHQ7g* numbers);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, decode_pwlTuBUQZhOuPNV9aDujQMg)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, NimStringDesc* hash);
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeInternal_D0RXiba7bli9byNMlD9bhjRg_2)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, tySequence_qwqHTkRvwhrRyENtudHQ7g* numbers);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, decodeInternal_9b1MvCVEpBYaVOaPnB9cziOA)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, NimStringDesc* hash, NimStringDesc* alphabet2);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, concat_kqTRt61Df52wxQcUXDS7aQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g** seqs, NI seqsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, consistentShuffle_lFUzNHGYrhyZVX9bIn9c57vg)(NimStringDesc* alphabet2, NimStringDesc* salt);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, hash_lFBkEmdqn9ai36bj2eJFBQg)(NI input2, NimStringDesc* alphabet);
N_LIB_PRIVATE N_NIMCALL(NI, unhash_YaVbuWQtvCq5lRKHd4wt6A)(NimStringDesc* input, NimStringDesc* alphabet);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, hashidsDatInit000)(void);
TNimType NTI_3vGmkkOywVgO5kalu8cNeg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_oFYJKP7L2EphXb9ajR83NJg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_3, "cfhistuCFHISTU", 14);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_4, "", 0);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_6, "\01216 <= len(h.alphabet) alphabet must contain at least ", 54);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_7, " unique characters", 18);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_8, " ", 1);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_9, "not contains(h.alphabet, \" \") alphabet cannot contain spaces", 60);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_17, "\\s+", 3);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_25, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890", 62);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_45, "[", 1);
STRING_LITERAL(TM_JzjprfzQ9b5VnrWvX9csgYmQ_46, "]", 1);
static N_NIMCALL(void, Marker_tyRef_oFYJKP7L2EphXb9ajR83NJg)(void* p, NI op) {
	tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* a;
	a = (tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*)p;
	nimGCvisit((void*)(*a).salt, op);
	nimGCvisit((void*)(*a).alphabet, op);
	nimGCvisit((void*)(*a).seps, op);
	nimGCvisit((void*)(*a).guards, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_10;
	NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_11;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3556, "system.nim");
	a = x.a;
	nimln_(3557, "system.nim");
	nimln_(3546, "system.nim");
	TM_JzjprfzQ9b5VnrWvX9csgYmQ_10 = subInt(x.b, a);
	TM_JzjprfzQ9b5VnrWvX9csgYmQ_11 = addInt((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_10), ((NI) 1));
	L = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_11);
	nimln_(3558, "system.nim");
	result = mnewString(((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_12;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_13;
				if (!(i_2 < L)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(3559, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_12 = addInt(i, a);
				if ((NU)((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_12)) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i] = s->data[(NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_12)];
				nimln_(3522, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_13 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_13);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qhashids)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_zG9bFJ68RP1XeAeJialvJfw)(NimStringDesc* salt, NI minHashLength, NimStringDesc* alphabet) {
	tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* result;
	tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* h;
	tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* uniqueAlphabet;
	NimStringDesc* T18_;
	tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* re1;
	NI guardCount;
	NF T69_;
	nimfr_("createHashids", "hashids.nim");
{	result = (tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*)0;
	nimln_(40, "hashids.nim");
	T1_ = (tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*)0;
	T1_ = (tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*) newObj((&NTI_oFYJKP7L2EphXb9ajR83NJg_), sizeof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg));
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).salt; (*T1_).salt = copyStringRC1(salt);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (NimStringDesc*)0;
	T3_ = (*T1_).seps; (*T1_).seps = copyStringRC1(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_3));
	if (T3_) nimGCunrefNoCycle(T3_);
	h = T1_;
	nimln_(41, "hashids.nim");
	{
		if (!(minHashLength < ((NI) 0))) goto LA6_;
		nimln_(42, "hashids.nim");
		(*h).minHashLength = ((NI) 0);
	}
	goto LA4_;
	LA6_: ;
	{
		nimln_(44, "hashids.nim");
		(*h).minHashLength = minHashLength;
	}
	LA4_: ;
	nimln_(46, "hashids.nim");
	uniqueAlphabet = copyString(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(47, "hashids.nim");
		colontmp_ = (alphabet ? (alphabet->Sup.len-1) : -1);
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_5;
				if (!(res <= colontmp_)) goto LA11;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(48, "hashids.nim");
				{
					NIM_BOOL T14_;
					NimStringDesc* T17_;
					if ((NU)(i) > (NU)(alphabet->Sup.len)) raiseIndexError();
					T14_ = (NIM_BOOL)0;
					T14_ = contains_6e5MGL10HDAJ205lBYpWxw(uniqueAlphabet, alphabet->data[i]);
					if (!!(T14_)) goto LA15_;
					nimln_(49, "hashids.nim");
					if ((NU)(i) > (NU)(alphabet->Sup.len)) raiseIndexError();
					T17_ = (NimStringDesc*)0;
					T17_ = nimCharToStr(alphabet->data[i]);
					uniqueAlphabet = resizeString(uniqueAlphabet, T17_->Sup.len + 0);
appendString(uniqueAlphabet, T17_);
				}
				LA15_: ;
				nimln_(2048, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_5 = addInt(res, ((NI) 1));
				res = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_5);
			} LA11: ;
		}
	}
	nimln_(50, "hashids.nim");
	T18_ = (NimStringDesc*)0;
	T18_ = (*h).alphabet; (*h).alphabet = copyStringRC1(uniqueAlphabet);
	if (T18_) nimGCunrefNoCycle(T18_);
	nimln_(52, "hashids.nim");
	{
		NimStringDesc* T23_;
		NimStringDesc* T24_;
		if (!!((((NI) 16) <= ((*h).alphabet ? (*h).alphabet->Sup.len : 0)))) goto LA21_;
		T23_ = (NimStringDesc*)0;
		T24_ = (NimStringDesc*)0;
		T24_ = nsuIntToStr(((NI) 16), ((NI) 1));
		T23_ = rawNewString(T24_->Sup.len + 72);
appendString(T23_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_6));
appendString(T23_, T24_);
appendString(T23_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_7));
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(T23_);
	}
	LA21_: ;
	nimln_(53, "hashids.nim");
	{
		NIM_BOOL T27_;
		T27_ = (NIM_BOOL)0;
		T27_ = contains_bKoQGynT9bWCEn79aXG8be9aw((*h).alphabet, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_8));
		if (!!(!(T27_))) goto LA28_;
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_9));
	}
	LA28_: ;
	{
		NI i_2;
		NI colontmp__2;
		NI res_2;
		i_2 = (NI)0;
		colontmp__2 = (NI)0;
		nimln_(55, "hashids.nim");
		colontmp__2 = ((*h).seps ? ((*h).seps->Sup.len-1) : -1);
		nimln_(2045, "system.nim");
		res_2 = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI j;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_16;
				if (!(res_2 <= colontmp__2)) goto LA32;
				nimln_(2047, "system.nim");
				i_2 = res_2;
				nimln_(56, "hashids.nim");
				if ((NU)(i_2) > (NU)((*h).seps->Sup.len)) raiseIndexError();
				j = nsuFindChar((*h).alphabet, (*h).seps->data[i_2], ((NI) 0), ((NI) 0));
				nimln_(57, "hashids.nim");
				{
					NimStringDesc* T37_;
					NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_14;
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T38_;
					NimStringDesc* T39_;
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T40_;
					NimStringDesc* T41_;
					if (!(j == ((NI) -1))) goto LA35_;
					nimln_(58, "hashids.nim");
					T37_ = (NimStringDesc*)0;
					TM_JzjprfzQ9b5VnrWvX9csgYmQ_14 = subInt(i_2, ((NI) 1));
					T38_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_14));
					T39_ = (NimStringDesc*)0;
					T39_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).seps, T38_);
					T40_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(i_2, ((*h).seps ? ((*h).seps->Sup.len-1) : -1));
					T41_ = (NimStringDesc*)0;
					T41_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).seps, T40_);
					T37_ = rawNewString(T39_->Sup.len + T41_->Sup.len + 1);
appendString(T37_, T39_);
appendString(T37_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_8));
appendString(T37_, T41_);
					asgnRefNoCycle((void**) (&(*h).seps), T37_);
				}
				goto LA33_;
				LA35_: ;
				{
					NimStringDesc* T43_;
					NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_15;
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T44_;
					NimStringDesc* T45_;
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T46_;
					NimStringDesc* T47_;
					nimln_(60, "hashids.nim");
					T43_ = (NimStringDesc*)0;
					TM_JzjprfzQ9b5VnrWvX9csgYmQ_15 = subInt(j, ((NI) 1));
					T44_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_15));
					T45_ = (NimStringDesc*)0;
					T45_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).alphabet, T44_);
					T46_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(j, ((*h).alphabet ? ((*h).alphabet->Sup.len-1) : -1));
					T47_ = (NimStringDesc*)0;
					T47_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).alphabet, T46_);
					T43_ = rawNewString(T45_->Sup.len + T47_->Sup.len + 1);
appendString(T43_, T45_);
appendString(T43_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_8));
appendString(T43_, T47_);
					asgnRefNoCycle((void**) (&(*h).alphabet), T43_);
				}
				LA33_: ;
				nimln_(2048, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_16 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_16);
			} LA32: ;
		}
	}
	nimln_(62, "hashids.nim");
	re1 = re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_17), 16);
	nimln_(63, "hashids.nim");
	asgnRefNoCycle((void**) (&(*h).alphabet), replace_XTFad3adT9ckW2xJiSYMhMw((*h).alphabet, re1, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4)));
	nimln_(64, "hashids.nim");
	asgnRefNoCycle((void**) (&(*h).seps), replace_XTFad3adT9ckW2xJiSYMhMw((*h).seps, re1, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4)));
	nimln_(66, "hashids.nim");
	{
		NIM_BOOL T50_;
		NF T52_;
		NI sepsLen;
		NF T55_;
		T50_ = (NIM_BOOL)0;
		T50_ = (((*h).seps) && ((*h).seps)->Sup.len == 0);
		if (T50_) goto LA51_;
		T52_ = (NF)0;
		T52_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((*h).alphabet ? (*h).alphabet->Sup.len : 0), ((*h).seps ? (*h).seps->Sup.len : 0));
		T50_ = (3.5000000000000000e+00 < T52_);
		LA51_: ;
		if (!T50_) goto LA53_;
		nimln_(67, "hashids.nim");
		T55_ = (NF)0;
		T55_ = ceil(((NF)(((NF) (((*h).alphabet ? (*h).alphabet->Sup.len : 0)))) / (NF)(3.5000000000000000e+00)));
		sepsLen = ((NI) (T55_));
		nimln_(69, "hashids.nim");
		{
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_18;
			if (!(sepsLen == ((NI) 1))) goto LA58_;
			nimln_(70, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_18 = addInt(sepsLen, ((NI) 1));
			sepsLen = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_18);
		}
		LA58_: ;
		nimln_(72, "hashids.nim");
		{
			NI diff;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_19;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_20;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T64_;
			NimStringDesc* T65_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_21;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T66_;
			if (!(((*h).seps ? (*h).seps->Sup.len : 0) < sepsLen)) goto LA62_;
			nimln_(73, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_19 = subInt(sepsLen, ((*h).seps ? (*h).seps->Sup.len : 0));
			diff = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_19);
			nimln_(74, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_20 = subInt(diff, ((NI) 1));
			T64_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_20));
			T65_ = (NimStringDesc*)0;
			T65_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).alphabet, T64_);
			(*h).seps = resizeString((*h).seps, T65_->Sup.len + 0);
appendString((*h).seps, T65_);
			nimln_(75, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_21 = subInt(diff, ((NI) 1));
			T66_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_21));
			asgnRefNoCycle((void**) (&(*h).alphabet), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).alphabet, T66_));
		}
		goto LA60_;
		LA62_: ;
		{
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_22;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T68_;
			nimln_(77, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_22 = subInt(sepsLen, ((NI) 1));
			T68_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_22));
			asgnRefNoCycle((void**) (&(*h).seps), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).seps, T68_));
		}
		LA60_: ;
	}
	LA53_: ;
	nimln_(79, "hashids.nim");
	asgnRefNoCycle((void**) (&(*h).alphabet), consistentShuffle_lFUzNHGYrhyZVX9bIn9c57vg((*h).alphabet, (*h).salt));
	nimln_(80, "hashids.nim");
	T69_ = (NF)0;
	T69_ = ceil(((NF)(((NF) (((*h).alphabet ? (*h).alphabet->Sup.len : 0)))) / (NF)(1.2000000000000000e+01)));
	guardCount = ((NI) (T69_));
	nimln_(82, "hashids.nim");
	{
		NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_23;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T74_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T75_;
		if (!(((*h).alphabet ? (*h).alphabet->Sup.len : 0) < ((NI) 3))) goto LA72_;
		nimln_(83, "hashids.nim");
		TM_JzjprfzQ9b5VnrWvX9csgYmQ_23 = subInt(guardCount, ((NI) 1));
		T74_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_23));
		asgnRefNoCycle((void**) (&(*h).guards), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).seps, T74_));
		nimln_(84, "hashids.nim");
		T75_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(guardCount, ((*h).seps ? ((*h).seps->Sup.len-1) : -1));
		asgnRefNoCycle((void**) (&(*h).seps), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).seps, T75_));
	}
	goto LA70_;
	LA72_: ;
	{
		NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_24;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T77_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T78_;
		nimln_(86, "hashids.nim");
		TM_JzjprfzQ9b5VnrWvX9csgYmQ_24 = subInt(guardCount, ((NI) 1));
		T77_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_24));
		asgnRefNoCycle((void**) (&(*h).guards), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).alphabet, T77_));
		nimln_(87, "hashids.nim");
		T78_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(guardCount, ((*h).alphabet ? ((*h).alphabet->Sup.len-1) : -1));
		asgnRefNoCycle((void**) (&(*h).alphabet), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*h).alphabet, T78_));
	}
	LA70_: ;
	nimln_(89, "hashids.nim");
	result = h;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_O07h2h9cUM2mHUfR3Dz1paA)(NimStringDesc* salt, NI minHashLength) {
	tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* result;
	nimfr_("createHashids", "hashids.nim");
{	result = (tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*)0;
	nimln_(96, "hashids.nim");
	result = createHashids_zG9bFJ68RP1XeAeJialvJfw(salt, minHashLength, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_25));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_whSPG9bOGCvpSoqgm7w29cbQ)(NimStringDesc* salt) {
	tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* result;
	nimfr_("createHashids", "hashids.nim");
{	result = (tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*)0;
	nimln_(103, "hashids.nim");
	result = createHashids_zG9bFJ68RP1XeAeJialvJfw(salt, ((NI) 0), ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_25));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*, createHashids_pHmRwdP59aPVoZIoyNFP9czg)(void) {
	tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* result;
	nimfr_("createHashids", "hashids.nim");
{	result = (tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*)0;
	nimln_(110, "hashids.nim");
	result = createHashids_zG9bFJ68RP1XeAeJialvJfw(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4), ((NI) 0), ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_25));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encode_D0RXiba7bli9byNMlD9bhjRg)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, tySequence_qwqHTkRvwhrRyENtudHQ7g* numbers) {
	NimStringDesc* result;
	NimStringDesc* retval;
	nimfr_("encode", "hashids.nim");
{	result = (NimStringDesc*)0;
	nimln_(117, "hashids.nim");
	retval = copyString(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
	nimln_(118, "hashids.nim");
	{
		NI T3_;
		T3_ = (numbers ? numbers->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(119, "hashids.nim");
		result = copyString(retval);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(120, "hashids.nim");
	result = encodeInternal_D0RXiba7bli9byNMlD9bhjRg_2(hashid, numbers);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	a = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)p;
	T1_ = (NI)0;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, decode_pwlTuBUQZhOuPNV9aDujQMg)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, NimStringDesc* hash) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* ret;
	nimfr_("decode", "hashids.nim");
{	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	nimln_(127, "hashids.nim");
	ret = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 0);
	nimln_(129, "hashids.nim");
	{
		if (!((hash) && (hash)->Sup.len == 0)) goto LA3_;
		nimln_(130, "hashids.nim");
		genericSeqAssign((&result), ret, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(132, "hashids.nim");
	result = decodeInternal_9b1MvCVEpBYaVOaPnB9cziOA(hashid, hash, (*hashid).alphabet);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeInternal_D0RXiba7bli9byNMlD9bhjRg_2)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, tySequence_qwqHTkRvwhrRyENtudHQ7g* numbers) {
	NimStringDesc* result;
	NI numberHashInt;
	NimStringDesc* alphabet;
	NimStringDesc* ret;
	NimStringDesc* T5_;
	NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_30;
	NimStringDesc* lottery;
	NI num;
	NI sepsIndex;
	NI guardIndex;
	NimStringDesc* buffer;
	NimStringDesc* retStr;
	NimStringDesc* guard;
	NI halfLen;
	NF T30_;
	nimfr_("encodeInternal", "hashids.nim");
{	result = (NimStringDesc*)0;
	nimln_(138, "hashids.nim");
	numberHashInt = ((NI) 0);
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(139, "hashids.nim");
		T2_ = (numbers ? (numbers->Sup.len-1) : -1);
		colontmp_ = T2_;
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_26;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_27;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_28;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_29;
				if (!(res <= colontmp_)) goto LA4;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(140, "hashids.nim");
				if ((NU)(i) >= (NU)(numbers->Sup.len)) raiseIndexError();
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_26 = addInt(i, ((NI) 100));
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_27 = modInt(numbers->data[i], (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_26));
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_28 = addInt(numberHashInt, (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_27));
				numberHashInt = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_28);
				nimln_(2048, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_29 = addInt(res, ((NI) 1));
				res = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_29);
			} LA4: ;
		}
	}
	nimln_(142, "hashids.nim");
	alphabet = copyString((*hashid).alphabet);
	nimln_(143, "hashids.nim");
	T5_ = (NimStringDesc*)0;
	TM_JzjprfzQ9b5VnrWvX9csgYmQ_30 = modInt(numberHashInt, (alphabet ? alphabet->Sup.len : 0));
	if ((NU)((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_30)) > (NU)(alphabet->Sup.len)) raiseIndexError();
	T5_ = rawNewString(1);
appendChar(T5_, alphabet->data[(NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_30)]);
appendString(T5_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
	ret = T5_;
	nimln_(144, "hashids.nim");
	lottery = copyString(ret);
	num = (NI)0;
	sepsIndex = (NI)0;
	guardIndex = (NI)0;
	nimln_(148, "hashids.nim");
	buffer = copyString(ret);
	nimln_(149, "hashids.nim");
	retStr = copyString(ret);
	guard = (NimStringDesc*)0;
	{
		NI i_2;
		NI colontmp__2;
		NI T7_;
		NI res_2;
		i_2 = (NI)0;
		colontmp__2 = (NI)0;
		nimln_(152, "hashids.nim");
		T7_ = (numbers ? (numbers->Sup.len-1) : -1);
		colontmp__2 = T7_;
		nimln_(2045, "system.nim");
		res_2 = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NimStringDesc* T10_;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_31;
				tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T11_;
				NimStringDesc* T12_;
				NimStringDesc* last;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_36;
				if (!(res_2 <= colontmp__2)) goto LA9;
				nimln_(2047, "system.nim");
				i_2 = res_2;
				nimln_(153, "hashids.nim");
				if ((NU)(i_2) >= (NU)(numbers->Sup.len)) raiseIndexError();
				num = numbers->data[i_2];
				nimln_(154, "hashids.nim");
				T10_ = (NimStringDesc*)0;
				T10_ = rawNewString(lottery->Sup.len + (*hashid).salt->Sup.len + alphabet->Sup.len + 0);
appendString(T10_, lottery);
appendString(T10_, (*hashid).salt);
appendString(T10_, alphabet);
				buffer = T10_;
				nimln_(156, "hashids.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_31 = subInt((alphabet ? alphabet->Sup.len : 0), ((NI) 1));
				T11_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_31));
				T12_ = (NimStringDesc*)0;
				T12_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(buffer, T11_);
				alphabet = consistentShuffle_lFUzNHGYrhyZVX9bIn9c57vg(alphabet, T12_);
				nimln_(157, "hashids.nim");
				last = hash_lFBkEmdqn9ai36bj2eJFBQg(num, alphabet);
				nimln_(159, "hashids.nim");
				retStr = resizeString(retStr, last->Sup.len + 0);
appendString(retStr, last);
				nimln_(161, "hashids.nim");
				{
					NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_32;
					NI T15_;
					NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_33;
					NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_34;
					NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_35;
					NimStringDesc* T18_;
					TM_JzjprfzQ9b5VnrWvX9csgYmQ_32 = addInt(i_2, ((NI) 1));
					T15_ = (numbers ? numbers->Sup.len : 0);
					if (!((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_32) < T15_)) goto LA16_;
					nimln_(162, "hashids.nim");
					if ((NU)(((NI) 0)) > (NU)(last->Sup.len)) raiseIndexError();
					TM_JzjprfzQ9b5VnrWvX9csgYmQ_33 = addInt(((NI) (((NU8)(last->data[((NI) 0)])))), i_2);
					TM_JzjprfzQ9b5VnrWvX9csgYmQ_34 = modInt(num, (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_33));
					num = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_34);
					nimln_(163, "hashids.nim");
					TM_JzjprfzQ9b5VnrWvX9csgYmQ_35 = modInt(num, ((*hashid).seps ? (*hashid).seps->Sup.len : 0));
					sepsIndex = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_35);
					nimln_(164, "hashids.nim");
					T18_ = (NimStringDesc*)0;
					if ((NU)(sepsIndex) > (NU)((*hashid).seps->Sup.len)) raiseIndexError();
					T18_ = rawNewString(1);
appendChar(T18_, (*hashid).seps->data[sepsIndex]);
appendString(T18_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
					retStr = resizeString(retStr, T18_->Sup.len + 0);
appendString(retStr, T18_);
				}
				LA16_: ;
				nimln_(2048, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_36 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_36);
			} LA9: ;
		}
	}
	nimln_(166, "hashids.nim");
	{
		NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_37;
		NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_38;
		NimStringDesc* T23_;
		NimStringDesc* T24_;
		if (!((retStr ? retStr->Sup.len : 0) < (*hashid).minHashLength)) goto LA21_;
		nimln_(167, "hashids.nim");
		if ((NU)(((NI) 0)) > (NU)(retStr->Sup.len)) raiseIndexError();
		TM_JzjprfzQ9b5VnrWvX9csgYmQ_37 = addInt(numberHashInt, ((NI) (((NU8)(retStr->data[((NI) 0)])))));
		TM_JzjprfzQ9b5VnrWvX9csgYmQ_38 = modInt((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_37), ((*hashid).guards ? (*hashid).guards->Sup.len : 0));
		guardIndex = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_38);
		nimln_(168, "hashids.nim");
		T23_ = (NimStringDesc*)0;
		if ((NU)(guardIndex) > (NU)((*hashid).guards->Sup.len)) raiseIndexError();
		T23_ = rawNewString(1);
appendChar(T23_, (*hashid).guards->data[guardIndex]);
appendString(T23_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
		guard = T23_;
		nimln_(170, "hashids.nim");
		T24_ = (NimStringDesc*)0;
		T24_ = rawNewString(guard->Sup.len + retStr->Sup.len + 0);
appendString(T24_, guard);
appendString(T24_, retStr);
		retStr = T24_;
		nimln_(172, "hashids.nim");
		{
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_39;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_40;
			NimStringDesc* T29_;
			if (!((retStr ? retStr->Sup.len : 0) < (*hashid).minHashLength)) goto LA27_;
			nimln_(173, "hashids.nim");
			if ((NU)(((NI) 2)) > (NU)(retStr->Sup.len)) raiseIndexError();
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_39 = addInt(numberHashInt, ((NI) (((NU8)(retStr->data[((NI) 2)])))));
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_40 = modInt((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_39), ((*hashid).guards ? (*hashid).guards->Sup.len : 0));
			guardIndex = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_40);
			nimln_(174, "hashids.nim");
			T29_ = (NimStringDesc*)0;
			if ((NU)(guardIndex) > (NU)((*hashid).guards->Sup.len)) raiseIndexError();
			T29_ = rawNewString(1);
appendChar(T29_, (*hashid).guards->data[guardIndex]);
appendString(T29_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
			guard = T29_;
			nimln_(176, "hashids.nim");
			retStr = resizeString(retStr, guard->Sup.len + 0);
appendString(retStr, guard);
		}
		LA27_: ;
	}
	LA21_: ;
	nimln_(178, "hashids.nim");
	T30_ = (NF)0;
	T30_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem((alphabet ? alphabet->Sup.len : 0), ((NI) 2));
	halfLen = ((NI) (T30_));
	{
		nimln_(179, "hashids.nim");
		while (1) {
			NimStringDesc* T33_;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T34_;
			NimStringDesc* T35_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_41;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T36_;
			NimStringDesc* T37_;
			NI excess;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_42;
			if (!((retStr ? retStr->Sup.len : 0) < (*hashid).minHashLength)) goto LA32;
			nimln_(180, "hashids.nim");
			alphabet = consistentShuffle_lFUzNHGYrhyZVX9bIn9c57vg(alphabet, alphabet);
			nimln_(181, "hashids.nim");
			T33_ = (NimStringDesc*)0;
			T34_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(halfLen, (alphabet ? (alphabet->Sup.len-1) : -1));
			T35_ = (NimStringDesc*)0;
			T35_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(alphabet, T34_);
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_41 = subInt(halfLen, ((NI) 1));
			T36_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_41));
			T37_ = (NimStringDesc*)0;
			T37_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(alphabet, T36_);
			T33_ = rawNewString(T35_->Sup.len + retStr->Sup.len + T37_->Sup.len + 0);
appendString(T33_, T35_);
appendString(T33_, retStr);
appendString(T33_, T37_);
			retStr = T33_;
			nimln_(182, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_42 = subInt((retStr ? retStr->Sup.len : 0), (*hashid).minHashLength);
			excess = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_42);
			nimln_(183, "hashids.nim");
			{
				NI startPos;
				NF T42_;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_43;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_44;
				tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T43_;
				if (!(((NI) 0) < excess)) goto LA40_;
				nimln_(184, "hashids.nim");
				T42_ = (NF)0;
				T42_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(excess, ((NI) 2));
				startPos = ((NI) (T42_));
				nimln_(185, "hashids.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_43 = addInt(startPos, (*hashid).minHashLength);
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_44 = subInt((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_43), ((NI) 1));
				T43_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(startPos, (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_44));
				retStr = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(retStr, T43_);
			}
			LA40_: ;
		} LA32: ;
	}
	nimln_(187, "hashids.nim");
	result = copyString(retStr);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, decodeInternal_9b1MvCVEpBYaVOaPnB9cziOA)(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg* hashid, NimStringDesc* hash, NimStringDesc* alphabet2) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	NimStringDesc* alphabet;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* ret;
	NI i;
	NimStringDesc* regexp;
	NimStringDesc* T1_;
	NimStringDesc* hashBreakdown;
	tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* T2_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* hashArray;
	NimStringDesc* lottery;
	NimStringDesc* T11_;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T12_;
	NimStringDesc* T13_;
	tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* T14_;
	NimStringDesc* subHash;
	NimStringDesc* buffer;
	nimfr_("decodeInternal", "hashids.nim");
{	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	nimln_(193, "hashids.nim");
	alphabet = copyString(alphabet2);
	nimln_(195, "hashids.nim");
	ret = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 0);
	nimln_(197, "hashids.nim");
	i = ((NI) 0);
	nimln_(198, "hashids.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString((*hashid).guards->Sup.len + 2);
appendString(T1_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_45));
appendString(T1_, (*hashid).guards);
appendString(T1_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_46));
	regexp = T1_;
	nimln_(199, "hashids.nim");
	T2_ = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
	T2_ = re_2TnOqvPvxix6tRYnuIeq9bw(regexp, 16);
	hashBreakdown = replace_XTFad3adT9ckW2xJiSYMhMw(hash, T2_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_8));
	nimln_(200, "hashids.nim");
	hashArray = nsuSplitString(hashBreakdown, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_8), ((NI) -1));
	nimln_(202, "hashids.nim");
	{
		NIM_BOOL T5_;
		NI T6_;
		NI T8_;
		T5_ = (NIM_BOOL)0;
		T6_ = (hashArray ? hashArray->Sup.len : 0);
		T5_ = (T6_ == ((NI) 3));
		if (T5_) goto LA7_;
		T8_ = (hashArray ? hashArray->Sup.len : 0);
		T5_ = (T8_ == ((NI) 2));
		LA7_: ;
		if (!T5_) goto LA9_;
		nimln_(203, "hashids.nim");
		i = ((NI) 1);
	}
	LA9_: ;
	nimln_(205, "hashids.nim");
	if ((NU)(i) >= (NU)(hashArray->Sup.len)) raiseIndexError();
	hashBreakdown = copyString(hashArray->data[i]);
	nimln_(207, "hashids.nim");
	T11_ = (NimStringDesc*)0;
	if ((NU)(((NI) 0)) > (NU)(hashBreakdown->Sup.len)) raiseIndexError();
	T11_ = rawNewString(1);
appendChar(T11_, hashBreakdown->data[((NI) 0)]);
appendString(T11_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
	lottery = T11_;
	nimln_(208, "hashids.nim");
	T12_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 1), (hashBreakdown ? (hashBreakdown->Sup.len-1) : -1));
	hashBreakdown = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(hashBreakdown, T12_);
	nimln_(209, "hashids.nim");
	T13_ = (NimStringDesc*)0;
	T13_ = rawNewString((*hashid).seps->Sup.len + 2);
appendString(T13_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_45));
appendString(T13_, (*hashid).seps);
appendString(T13_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_46));
	T14_ = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
	T14_ = re_2TnOqvPvxix6tRYnuIeq9bw(T13_, 16);
	hashBreakdown = replace_XTFad3adT9ckW2xJiSYMhMw(hashBreakdown, T14_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_8));
	nimln_(210, "hashids.nim");
	hashArray = nsuSplitString(hashBreakdown, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_8), ((NI) -1));
	nimln_(212, "hashids.nim");
	subHash = copyString(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
	nimln_(213, "hashids.nim");
	buffer = copyString(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
	{
		NI j;
		NI colontmp_;
		NI T16_;
		NI res;
		j = (NI)0;
		colontmp_ = (NI)0;
		nimln_(214, "hashids.nim");
		T16_ = (hashArray ? (hashArray->Sup.len-1) : -1);
		colontmp_ = T16_;
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NimStringDesc* T19_;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_47;
				tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T20_;
				NimStringDesc* T21_;
				tyArray_pr9btTEBWiYSIlBNDlIa66w T22_;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_48;
				if (!(res <= colontmp_)) goto LA18;
				nimln_(2047, "system.nim");
				j = res;
				nimln_(215, "hashids.nim");
				if ((NU)(j) >= (NU)(hashArray->Sup.len)) raiseIndexError();
				subHash = copyString(hashArray->data[j]);
				nimln_(216, "hashids.nim");
				T19_ = (NimStringDesc*)0;
				T19_ = rawNewString(lottery->Sup.len + (*hashid).salt->Sup.len + alphabet->Sup.len + 0);
appendString(T19_, lottery);
appendString(T19_, (*hashid).salt);
appendString(T19_, alphabet);
				buffer = T19_;
				nimln_(217, "hashids.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_47 = subInt((alphabet ? alphabet->Sup.len : 0), ((NI) 1));
				T20_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_47));
				T21_ = (NimStringDesc*)0;
				T21_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(buffer, T20_);
				alphabet = consistentShuffle_lFUzNHGYrhyZVX9bIn9c57vg(alphabet, T21_);
				nimln_(218, "hashids.nim");
				memset((void*)T22_, 0, sizeof(T22_));
				genericSeqAssign((&T22_[0]), ret, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
				T22_[1] = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 1);
				T22_[1]->data[0] = unhash_YaVbuWQtvCq5lRKHd4wt6A(subHash, alphabet);
				ret = concat_kqTRt61Df52wxQcUXDS7aQ(T22_, 2);
				nimln_(2048, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_48 = addInt(res, ((NI) 1));
				res = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_48);
			} LA18: ;
		}
	}
	nimln_(220, "hashids.nim");
	genericSeqAssign((&result), ret, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, consistentShuffle_lFUzNHGYrhyZVX9bIn9c57vg)(NimStringDesc* alphabet2, NimStringDesc* salt) {
	NimStringDesc* result;
	NimStringDesc* alphabet;
	NI ascVal;
	NI j;
	NimStringDesc* temp;
	NI i;
	NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_49;
	NI v;
	NI p;
	nimfr_("consistentShuffle", "hashids.nim");
{	result = (NimStringDesc*)0;
	nimln_(226, "hashids.nim");
	alphabet = copyString(alphabet2);
	nimln_(228, "hashids.nim");
	{
		if (!((salt ? salt->Sup.len : 0) <= ((NI) 0))) goto LA3_;
		nimln_(229, "hashids.nim");
		result = copyString(alphabet);
		goto BeforeRet_;
	}
	LA3_: ;
	ascVal = (NI)0;
	j = (NI)0;
	temp = (NimStringDesc*)0;
	nimln_(234, "hashids.nim");
	TM_JzjprfzQ9b5VnrWvX9csgYmQ_49 = subInt((alphabet ? alphabet->Sup.len : 0), ((NI) 1));
	i = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_49);
	nimln_(235, "hashids.nim");
	v = ((NI) 0);
	nimln_(236, "hashids.nim");
	p = ((NI) 0);
	{
		nimln_(237, "hashids.nim");
		while (1) {
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_50;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_51;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_52;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_53;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_54;
			NimStringDesc* T7_;
			NimStringDesc* T8_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_55;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T9_;
			NimStringDesc* T10_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_56;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T11_;
			NimStringDesc* T12_;
			NimStringDesc* T13_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_57;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T14_;
			NimStringDesc* T15_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_58;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T16_;
			NimStringDesc* T17_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_59;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_60;
			if (!(((NI) 0) < i)) goto LA6;
			nimln_(239, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_50 = modInt(v, (salt ? salt->Sup.len : 0));
			v = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_50);
			nimln_(240, "hashids.nim");
			if ((NU)(v) > (NU)(salt->Sup.len)) raiseIndexError();
			ascVal = ((NI) (((NU8)(salt->data[v]))));
			nimln_(241, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_51 = addInt(p, ascVal);
			p = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_51);
			nimln_(242, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_52 = addInt(ascVal, v);
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_53 = addInt((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_52), p);
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_54 = modInt((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_53), i);
			j = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_54);
			nimln_(244, "hashids.nim");
			T7_ = (NimStringDesc*)0;
			if ((NU)(j) > (NU)(alphabet->Sup.len)) raiseIndexError();
			T7_ = rawNewString(1);
appendChar(T7_, alphabet->data[j]);
appendString(T7_, ((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
			temp = T7_;
			nimln_(245, "hashids.nim");
			T8_ = (NimStringDesc*)0;
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_55 = subInt(i, ((NI) 1));
			T9_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_55));
			T10_ = (NimStringDesc*)0;
			T10_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(alphabet, T9_);
			if ((NU)(i) > (NU)(alphabet->Sup.len)) raiseIndexError();
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_56 = addInt(j, ((NI) 1));
			T11_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_56), (alphabet ? (alphabet->Sup.len-1) : -1));
			T12_ = (NimStringDesc*)0;
			T12_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(alphabet, T11_);
			T8_ = rawNewString(T10_->Sup.len + T12_->Sup.len + 1);
appendString(T8_, T10_);
appendChar(T8_, alphabet->data[i]);
appendString(T8_, T12_);
			alphabet = T8_;
			nimln_(246, "hashids.nim");
			T13_ = (NimStringDesc*)0;
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_57 = subInt(i, ((NI) 1));
			T14_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids(((NI) 0), (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_57));
			T15_ = (NimStringDesc*)0;
			T15_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(alphabet, T14_);
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_58 = addInt(i, ((NI) 1));
			T16_ = dotdot__vDQySKWzgnxQdUarow6k5Qhashids((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_58), (alphabet ? (alphabet->Sup.len-1) : -1));
			T17_ = (NimStringDesc*)0;
			T17_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(alphabet, T16_);
			T13_ = rawNewString(T15_->Sup.len + temp->Sup.len + T17_->Sup.len + 0);
appendString(T13_, T15_);
appendString(T13_, temp);
appendString(T13_, T17_);
			alphabet = T13_;
			nimln_(248, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_59 = subInt(i, ((NI) 1));
			i = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_59);
			nimln_(249, "hashids.nim");
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_60 = addInt(v, ((NI) 1));
			v = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_60);
		} LA6: ;
	}
	nimln_(251, "hashids.nim");
	result = copyString(alphabet);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, hash_lFBkEmdqn9ai36bj2eJFBQg)(NI input2, NimStringDesc* alphabet) {
	NimStringDesc* result;
	NI input;
	NimStringDesc* hash;
	NI alphabetLen;
	NimStringDesc* T1_;
	NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_61;
	NF T2_;
	nimfr_("hash", "hashids.nim");
{	result = (NimStringDesc*)0;
	nimln_(257, "hashids.nim");
	input = input2;
	nimln_(258, "hashids.nim");
	hash = copyString(((NimStringDesc*) &TM_JzjprfzQ9b5VnrWvX9csgYmQ_4));
	nimln_(259, "hashids.nim");
	alphabetLen = (alphabet ? alphabet->Sup.len : 0);
	nimln_(261, "hashids.nim");
	T1_ = (NimStringDesc*)0;
	TM_JzjprfzQ9b5VnrWvX9csgYmQ_61 = modInt(input, alphabetLen);
	if ((NU)((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_61)) > (NU)(alphabet->Sup.len)) raiseIndexError();
	T1_ = rawNewString(hash->Sup.len + 1);
appendChar(T1_, alphabet->data[(NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_61)]);
appendString(T1_, hash);
	hash = T1_;
	nimln_(262, "hashids.nim");
	T2_ = (NF)0;
	T2_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(input, alphabetLen);
	input = ((NI) (T2_));
	{
		nimln_(264, "hashids.nim");
		while (1) {
			NimStringDesc* T5_;
			NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_62;
			NF T6_;
			if (!(((NI) 0) < input)) goto LA4;
			nimln_(265, "hashids.nim");
			T5_ = (NimStringDesc*)0;
			TM_JzjprfzQ9b5VnrWvX9csgYmQ_62 = modInt(input, alphabetLen);
			if ((NU)((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_62)) > (NU)(alphabet->Sup.len)) raiseIndexError();
			T5_ = rawNewString(hash->Sup.len + 1);
appendChar(T5_, alphabet->data[(NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_62)]);
appendString(T5_, hash);
			hash = T5_;
			nimln_(266, "hashids.nim");
			T6_ = (NF)0;
			T6_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(input, alphabetLen);
			input = ((NI) (T6_));
		} LA4: ;
	}
	nimln_(268, "hashids.nim");
	result = copyString(hash);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, unhash_YaVbuWQtvCq5lRKHd4wt6A)(NimStringDesc* input, NimStringDesc* alphabet) {
	NI result;
	NI number;
	NI pos;
	nimfr_("unhash", "hashids.nim");
{	result = (NI)0;
	nimln_(274, "hashids.nim");
	number = ((NI) 0);
	pos = (NI)0;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(277, "hashids.nim");
		colontmp_ = (input ? (input->Sup.len-1) : -1);
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_63;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_64;
				NF T4_;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_65;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_66;
				NI TM_JzjprfzQ9b5VnrWvX9csgYmQ_67;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(278, "hashids.nim");
				if ((NU)(i) > (NU)(input->Sup.len)) raiseIndexError();
				pos = nsuFindChar(alphabet, input->data[i], ((NI) 0), ((NI) 0));
				nimln_(279, "hashids.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_63 = subInt((input ? input->Sup.len : 0), i);
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_64 = subInt((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_63), ((NI) 1));
				T4_ = (NF)0;
				T4_ = pow(((NF) ((alphabet ? alphabet->Sup.len : 0))), ((NF) ((NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_64))));
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_65 = mulInt(pos, ((NI) (T4_)));
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_66 = addInt(number, (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_65));
				number = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_66);
				nimln_(2048, "system.nim");
				TM_JzjprfzQ9b5VnrWvX9csgYmQ_67 = addInt(res, ((NI) 1));
				res = (NI)(TM_JzjprfzQ9b5VnrWvX9csgYmQ_67);
			} LA3: ;
		}
	}
	nimln_(281, "hashids.nim");
	result = number;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_pcreDatInit000();
	stdlib_rtarraysDatInit000();
	stdlib_reDatInit000();
	hashidsDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	stdlib_pcreInit000();
	stdlib_rtarraysInit000();
	stdlib_reInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("hashids", "hashids.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, hashidsDatInit000)(void) {
static TNimNode* TM_JzjprfzQ9b5VnrWvX9csgYmQ_2[5];
static TNimNode TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[6];
NTI_3vGmkkOywVgO5kalu8cNeg_.size = sizeof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg);
NTI_3vGmkkOywVgO5kalu8cNeg_.kind = 18;
NTI_3vGmkkOywVgO5kalu8cNeg_.base = 0;
NTI_3vGmkkOywVgO5kalu8cNeg_.flags = 2;
TM_JzjprfzQ9b5VnrWvX9csgYmQ_2[0] = &TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[1];
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[1].kind = 1;
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[1].offset = offsetof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg, salt);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[1].name = "salt";
TM_JzjprfzQ9b5VnrWvX9csgYmQ_2[1] = &TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[2];
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[2].kind = 1;
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[2].offset = offsetof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg, minHashLength);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[2].name = "minHashLength";
TM_JzjprfzQ9b5VnrWvX9csgYmQ_2[2] = &TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[3];
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[3].kind = 1;
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[3].offset = offsetof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg, alphabet);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[3].name = "alphabet";
TM_JzjprfzQ9b5VnrWvX9csgYmQ_2[3] = &TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[4];
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[4].kind = 1;
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[4].offset = offsetof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg, seps);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[4].name = "seps";
TM_JzjprfzQ9b5VnrWvX9csgYmQ_2[4] = &TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[5];
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[5].kind = 1;
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[5].offset = offsetof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg, guards);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[5].name = "guards";
TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[0].len = 5; TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[0].kind = 2; TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[0].sons = &TM_JzjprfzQ9b5VnrWvX9csgYmQ_2[0];
NTI_3vGmkkOywVgO5kalu8cNeg_.node = &TM_JzjprfzQ9b5VnrWvX9csgYmQ_0[0];
NTI_oFYJKP7L2EphXb9ajR83NJg_.size = sizeof(tyObject_HashidscolonObjectType__3vGmkkOywVgO5kalu8cNeg*);
NTI_oFYJKP7L2EphXb9ajR83NJg_.kind = 22;
NTI_oFYJKP7L2EphXb9ajR83NJg_.base = (&NTI_3vGmkkOywVgO5kalu8cNeg_);
NTI_oFYJKP7L2EphXb9ajR83NJg_.flags = 2;
NTI_oFYJKP7L2EphXb9ajR83NJg_.marker = Marker_tyRef_oFYJKP7L2EphXb9ajR83NJg;
NTI_qwqHTkRvwhrRyENtudHQ7g_.size = sizeof(tySequence_qwqHTkRvwhrRyENtudHQ7g*);
NTI_qwqHTkRvwhrRyENtudHQ7g_.kind = 24;
NTI_qwqHTkRvwhrRyENtudHQ7g_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_qwqHTkRvwhrRyENtudHQ7g_.flags = 2;
NTI_qwqHTkRvwhrRyENtudHQ7g_.marker = Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g;
}

